version: '3.8'

services:
  web:
    build: .
    ports:
      - "7001:7000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

